### PR TITLE
Readme instead submodules

### LINKED ISSUE #7: Rewrite submodules to git diff
1. Add git diffs in readme between example branch and main branch
2. Add github actions that rebases example with main branch after main is pushed

Also, think how to keep `saleor app create --example ...` feature if we remove submodules

### PR DESCRIPTION
**Pull request by krzysztofwolski**
Submodules are not exactly easy to use. Moved our examples to readme and added more context for the readers.

Close #7

### CODE REVIEW

**Comment by lkostrowski** [comment]
@krzysztofwolski please try dev build of CLI, probably `--example` is broken with this change. Maybe we can drop this command and leave `--branch` only

**Review by lkostrowski — CHANGES_REQUESTED** [review]
Waiting to confirm CLI behavior

**Comment by lkostrowski** [comment]
Lets freeze this until we decide where and how we keep our content database

**Comment by lkostrowski** [comment]
@krzysztofwolski we can add readme, but lets keep submodules now

**Comment by 2can** [comment]
@lkostrowski @krzysztofwolski CLI can work directly on `saleor-app-template` branches

**Pull request closed without merging**
